/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Views;

import DTO.Persona;
import DTO.Vendedor;

/**
 *
 * @author Cetecom
 */
public class vwVendedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form vwVendedor
     */
    public vwVendedor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomVende = new javax.swing.JLabel();
        lblRutVende = new javax.swing.JLabel();
        lblFonoVende = new javax.swing.JLabel();
        lblDirVende = new javax.swing.JLabel();
        lblCorreoVende = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txtRutVen = new javax.swing.JTextField();
        txtFonoVen = new javax.swing.JTextField();
        txtNomVen = new javax.swing.JTextField();
        txtDirVen = new javax.swing.JTextField();
        txtCorreoVen = new javax.swing.JTextField();
        lblVen = new javax.swing.JLabel();

        setClosable(true);

        lblNomVende.setText("Nombre:");

        lblRutVende.setText("Rut:");

        lblFonoVende.setText("Fono:");

        lblDirVende.setText("Dirección:");

        lblCorreoVende.setText("Correo:");

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        txtRutVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRutVenActionPerformed(evt);
            }
        });

        txtFonoVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFonoVenActionPerformed(evt);
            }
        });

        txtNomVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomVenActionPerformed(evt);
            }
        });

        txtDirVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDirVenActionPerformed(evt);
            }
        });

        txtCorreoVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoVenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNomVende)
                        .addGap(18, 18, 18)
                        .addComponent(txtNomVen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRutVende)
                        .addGap(18, 18, 18)
                        .addComponent(txtRutVen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblFonoVende)
                        .addGap(18, 18, 18)
                        .addComponent(txtFonoVen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDirVende)
                        .addGap(18, 18, 18)
                        .addComponent(txtDirVen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblVen)
                            .addComponent(lblCorreoVende))
                        .addGap(18, 18, 18)
                        .addComponent(txtCorreoVen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(195, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomVende)
                    .addComponent(txtNomVen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRutVende)
                    .addComponent(txtRutVen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFonoVende)
                    .addComponent(txtFonoVen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDirVende)
                    .addComponent(txtDirVen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreoVende)
                    .addComponent(txtCorreoVen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir)
                    .addComponent(btnAceptar))
                .addGap(18, 18, 18)
                .addComponent(lblVen)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        String rutVen = txtRutVen.getText();
        String nombreVen = txtNomVen.getText();
        String fonoVen = txtFonoVen.getText();
        String dirVen = txtDirVen.getText();
        String correoVen = txtCorreoVen.getText();
        
        Persona ven1 = new Vendedor();
        ven1.getNombre();
        ven1.getRut();
        ven1.getCorreo();
        ven1.getFono();
   
        
        
        lblVen.setText("/nRut vendedor:"+ven1.getNombre()+
              "/nNombre Vendedor: "+ ven1.getRut()+
               "/nTeléfono vendedor: "+ ven1.getFono()+
               /// "/nDirección Vendedor"+ven1. +
                "/nCorreo electrónico vendedor: "+ven1.getCorreo() );
        
        
        
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtRutVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRutVenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRutVenActionPerformed

    private void txtFonoVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFonoVenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFonoVenActionPerformed

    private void txtNomVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomVenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomVenActionPerformed

    private void txtDirVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDirVenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDirVenActionPerformed

    private void txtCorreoVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoVenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoVenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel lblCorreoVende;
    private javax.swing.JLabel lblDirVende;
    private javax.swing.JLabel lblFonoVende;
    private javax.swing.JLabel lblNomVende;
    private javax.swing.JLabel lblRutVende;
    private javax.swing.JLabel lblVen;
    private javax.swing.JTextField txtCorreoVen;
    private javax.swing.JTextField txtDirVen;
    private javax.swing.JTextField txtFonoVen;
    private javax.swing.JTextField txtNomVen;
    private javax.swing.JTextField txtRutVen;
    // End of variables declaration//GEN-END:variables
}
